// 목업 데이터 + 화면 전역 상수. 실 API로 대체된 데이터(예: 예전 DREAM_FACILITIES)는
// 여기서 지워지는 게 정상 — 이 파일이 자꾸 비어가는 게 이 리팩터링의 목표다.
import {
  BadgePercent,
  Bike,
  BookOpen,
  CakeSlice,
  Dumbbell,
  Footprints,
  GraduationCap,
  ShieldAlert,
  SprayCan,
  TrainFront,
  Truck,
  Utensils,
} from "lucide-react";
import type { AlbaItem, CommunityPost, DangerTone, DangerVisual, LocalBusiness, LocalCategory, ProductListItem } from "./types";

export const PRODUCT_FILTERS = ["전체", "중고차", "알바", "중고거래", "부동산", "기타 서비스"];
export const COMMUNITY_TABS = ["전체", "자유 주제", "같이해요", "질문", "동네 정보"];
export const COMMUNITY_FILTERS = ["추천", "인기", "취미/여가", "운동/스포츠", "맛집/음식", "동네친구", "일반"];
export const CHAT_FILTERS = ["전체", "판매", "구매", "안읽음", "모임", "알바"];

export const NAVER_MAP_SCRIPT_ID = "naver-map-sdk";
export const NAVER_MAP_KEY_ID = process.env.NEXT_PUBLIC_NAVER_MAP_NCP_KEY_ID ?? "";
export const KAKAO_MAP_JS_KEY = process.env.NEXT_PUBLIC_KAKAO_JS_KEY ?? "";
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";

export const NEIGHBORHOOD_COORDS: Record<string, { lat: number; lng: number }> = {
  송파삼성래미안: { lat: 37.504744, lng: 127.118295 },
  위례: { lat: 37.4772, lng: 127.1437 },
  공릉: { lat: 37.6257, lng: 127.0731 },
  "당산 2동": { lat: 37.5351, lng: 126.9028 },
  문래동: { lat: 37.5177, lng: 126.8945 },
};

export const NEIGHBORHOOD_DISTRICTS: Record<string, string> = {
  송파삼성래미안: "송파구",
  위례: "송파구",
  공릉: "노원구",
  "당산 2동": "영등포구",
  문래동: "영등포구",
};

export const DANGER_VISUALS: Record<DangerTone, DangerVisual> = {
  fire: { label: "화재", emoji: "🔥", tone: "fire" },
  accident: { label: "사고", emoji: "⚠️", tone: "accident" },
  construction: { label: "공사", emoji: "🚧", tone: "construction" },
  failure: { label: "고장", emoji: "🔧", tone: "failure" },
  control: { label: "통제", emoji: "⛔", tone: "control" },
  flood: { label: "침수", emoji: "🌊", tone: "flood" },
  default: { label: "위험", emoji: "🚨", tone: "default" },
};

export const THEME_STORAGE_KEY = "carrot-theme";

export const initialProducts: ProductListItem[] = [
  {
    id: "p1",
    title: "삼성 갤럭시 탭 A7 SM-T505N",
    thumbnailLabel: "A7",
    thumbnailTone: "tablet",
    neighborhoodName: "위례",
    distanceKm: 3,
    createdAt: "17시간 전",
    price: 50000,
    tradeStatus: "RESERVED",
    tradeType: "SALE",
    purchaseMode: "NORMAL",
    chatCount: 1,
    favoriteCount: 9,
    viewCount: 214,
    interestCount: 0,
    isFavorite: true,
    mine: false,
    category: "중고거래",
    description: "케이스와 충전 케이블 함께 드립니다. 생활 기스는 조금 있지만 화면과 배터리 상태는 양호합니다.",
  },
  {
    id: "p2",
    title: "갤럭시 탭 a7 라이트",
    thumbnailLabel: "TAB",
    thumbnailTone: "screen",
    neighborhoodName: "공릉",
    distanceKm: 2,
    createdAt: "2일 전",
    price: 100000,
    tradeStatus: "SALE",
    tradeType: "SALE",
    purchaseMode: "DIRECT",
    chatCount: 4,
    favoriteCount: 4,
    viewCount: 96,
    interestCount: 0,
    isFavorite: false,
    mine: false,
    category: "중고거래",
    description: "필름 부착 상태로 사용했습니다. 영상 감상용으로 좋아요. 직거래는 지하철역 근처를 선호합니다.",
  },
  {
    id: "p3",
    title: "버거킹 할인 쿠폰 무료나눔",
    thumbnailLabel: "쿠폰",
    thumbnailTone: "coupon",
    neighborhoodName: "당산 2동",
    distanceKm: 1,
    createdAt: "2일 전",
    price: null,
    tradeStatus: "SALE",
    tradeType: "FREE",
    chatCount: 5,
    favoriteCount: 0,
    viewCount: 58,
    interestCount: 0,
    isFavorite: false,
    mine: true,
    category: "기타 서비스",
    description: "오늘 안에 사용 가능한 쿠폰입니다. 필요하신 분께 채팅으로 전달드릴게요.",
  },
  {
    id: "p4",
    title: "(세차) 세린이 모여라",
    thumbnailLabel: "세차",
    thumbnailTone: "carwash",
    neighborhoodName: "위례",
    createdAt: "17시간 전",
    price: null,
    tradeStatus: "SALE",
    tradeType: "FREE",
    chatCount: 0,
    favoriteCount: 9,
    viewCount: 131,
    interestCount: 0,
    isFavorite: false,
    mine: false,
    category: "중고차",
    description: "동네 셀프세차장 같이 가실 분을 찾습니다. 초보 환영입니다.",
  },
  {
    id: "p5",
    title: "원목 사이드 테이블",
    thumbnailLabel: "테이블",
    thumbnailTone: "wood",
    neighborhoodName: "공릉",
    distanceKm: 1,
    createdAt: "방금 전",
    price: 28000,
    tradeStatus: "SALE",
    tradeType: "SALE",
    chatCount: 0,
    favoriteCount: 2,
    viewCount: 19,
    interestCount: 0,
    isFavorite: false,
    mine: true,
    category: "중고거래",
    description: "작은 흠집이 있어 저렴하게 올립니다. 엘리베이터 앞 거래 가능합니다.",
  },
];

export const initialPosts: CommunityPost[] = [
  {
    id: "cpost1",
    categoryName: "일반",
    title: "이 사람 조심하세요",
    contentPreview: "별의별 사람이 다 있네요. 거래 전에 약속 장소와 시간을 꼭 확인해보세요.",
    thumbnailTone: "memo",
    thumbnailCount: 2,
    neighborhoodName: "위례",
    createdAt: "10분 전",
    viewCount: 139,
    commentCount: 0,
    reactionCount: 4,
  },
  {
    id: "cpost2",
    categoryName: "카페",
    title: "반년 전에 일했던 알바가 10만원 달라고 함",
    contentPreview: "신중하게 확인해야 할 일이 생겼어요. 비슷한 경험 있으신 분들 의견 부탁드려요.",
    thumbnailTone: "article",
    thumbnailCount: 1,
    neighborhoodName: "공릉",
    createdAt: "2시간 전",
    viewCount: 438,
    commentCount: 2,
    reactionCount: 12,
  },
  {
    id: "cpost3",
    categoryName: "동네친구",
    title: "영화 보러 갈 사람",
    contentPreview: "오디세이 보고 싶은데 친구가 없어요. 저 또래가 편해서 20대 환영해요.",
    neighborhoodName: "당산 2동",
    createdAt: "58분 전",
    viewCount: 72,
    commentCount: 0,
    reactionCount: 1,
  },
  {
    id: "cpost4",
    categoryName: "취미",
    title: "오늘 시간 되는 분",
    contentPreview: "동네 산책하고 커피 마실 분 있나요. 가볍게 이야기 나눌 수 있으면 좋아요.",
    neighborhoodName: "당산 2동",
    createdAt: "1시간 전",
    viewCount: 54,
    commentCount: 4,
    reactionCount: 9,
  },
];

export const LOCAL_CATEGORIES: LocalCategory[] = [
  { id: "food", name: "음식점", icon: Utensils, tone: "orange" },
  { id: "congestion", name: "혼잡도 분석", icon: Footprints, tone: "cyan" },
  { id: "subway", name: "지하철", icon: TrainFront, tone: "blue" },
  { id: "bike", name: "따릉이", icon: Bike, tone: "green" },
  { id: "danger", name: "위험", icon: ShieldAlert, tone: "rose" },
  { id: "takeout", name: "포장주문", icon: Utensils, tone: "amber" },
  { id: "sale", name: "할인중", icon: BadgePercent, tone: "orange" },
  { id: "workout", name: "운동", icon: Dumbbell, tone: "cyan" },
  { id: "lesson", name: "레슨/과외", icon: BookOpen, tone: "rose" },
  { id: "class", name: "클래스", icon: CakeSlice, tone: "amber" },
  { id: "academy", name: "학원", icon: GraduationCap, tone: "sky" },
  { id: "clean", name: "청소", icon: SprayCan, tone: "green" },
  { id: "delivery", name: "용달", icon: Truck, tone: "blue" },
];

export const LOCAL_BUSINESSES: LocalBusiness[] = [
  {
    id: "danger1",
    name: "송파구 침수·집중호우 주의구역",
    category: "danger",
    neighborhoodName: "송파삼성래미안",
    distance: "120m",
    openNow: true,
    liked: false,
    summary: "실시간 재난안전: 하천변 발자국 및 보행 유의",
    lat: 37.5052,
    lng: 127.1188,
  },
  {
    id: "danger2",
    name: "공릉동 야간 통행 위험구역",
    category: "danger",
    neighborhoodName: "공릉",
    distance: "350m",
    openNow: true,
    liked: false,
    summary: "안전정보: 도로 가스배관 공사 중 (서행 필요)",
    lat: 37.6262,
    lng: 127.0741,
  },
  {
    id: "b1",
    name: "당산 2동 작은식탁",
    category: "food",
    neighborhoodName: "당산 2동",
    distance: "320m",
    openNow: true,
    liked: true,
    summary: "오늘 포장 주문 10% 할인",
    lat: 37.5351,
    lng: 126.9028,
  },
  {
    id: "b2",
    name: "위례 코드 과외",
    category: "lesson",
    neighborhoodName: "위례",
    distance: "850m",
    openNow: true,
    liked: false,
    summary: "초등부터 성인까지 1:1 수업",
    lat: 37.4775,
    lng: 127.1452,
  },
  {
    id: "b3",
    name: "공릉 클린홈",
    category: "clean",
    neighborhoodName: "공릉",
    distance: "1.1km",
    openNow: false,
    liked: false,
    summary: "입주 청소와 정기 청소 예약 가능",
    lat: 37.6257,
    lng: 127.0731,
  },
  {
    id: "b4",
    name: "위례 모닝카페",
    category: "cafe",
    neighborhoodName: "위례",
    distance: "540m",
    openNow: true,
    liked: true,
    summary: "아메리카노 테이크아웃 쿠폰 제공",
    lat: 37.4788,
    lng: 127.1418,
  },
  {
    id: "b5",
    name: "송파 래미안 픽업",
    category: "takeout",
    neighborhoodName: "송파삼성래미안",
    distance: "120m",
    openNow: true,
    liked: false,
    summary: "단지 근처 포장 주문 가능",
    lat: 37.5051,
    lng: 127.1187,
  },
];

export const baseMessages = [
  { mine: false, text: "안녕하세요. 아직 거래 가능할까요?", time: "오후 5:11" },
  { mine: true, text: "네 가능해요. 오늘 저녁에도 괜찮습니다.", time: "오후 5:14" },
  { mine: false, text: "그럼 7시에 위례 주민센터 앞에서 뵐게요.", time: "오후 5:18" },
];

export const ALBA_MOCK_DATA: AlbaItem[] = [
  {
    id: "alba-1",
    title: "[무신사스탠다드] 명동중앙점 풀타임 스태프 채용",
    companyName: "무신사 스탠다드 명동중앙점",
    neighborhoodName: "중구 충무로1가",
    detailLocation: "명동역 6번 출구 도보 2분",
    payType: "연봉",
    payAmount: 27600000,
    payLabel: "연봉 2,760만원",
    workingDays: "주 5일 (스케줄 근무)",
    workingHours: "09:30 ~ 19:30 (휴게 1시간)",
    category: "이웃알바",
    badges: ["정직원", "모범구인"],
    reviewCount: 4,
    thumbnailTone: "musinsa",
    thumbnailEmoji: "🏢",
    bgGradient: "linear-gradient(135deg, #1c1d22 0%, #363942 100%)",
    descriptionBullets: [
      "1. 매장 상품 진열 및 고객 응대",
      "2. 피팅룸 안내 및 재고 관리",
      "3. 4대보험, 퇴직금, 유니폼 지원",
      "4. 무신사 패밀리 임직원 할인 혜택"
    ],
    details: "트렌디한 패션 브랜드 무신사 스탠다드 명동점에서 함께할 열정적인 스태프를 모십니다. 패션에 관심이 많고 친절한 분들의 많은 지원 바랍니다!",
    applicantCount: 8,
    viewCount: 412,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "02-1544-7199",
    isAd: true,
    createdAt: "방금 전",
  },
  {
    id: "alba-2",
    title: "명동뷰티매장 질서유지 및 고객응대",
    companyName: "휴먼코드",
    neighborhoodName: "중구 충무로1가",
    detailLocation: "명동역 6번출구 도보 1분거리 올리브영 명동본점",
    payType: "일급",
    payAmount: 65000,
    payLabel: "일급 65,000원",
    workingDays: "월~금",
    workingHours: "18:00 ~ 22:30",
    category: "단기알바",
    badges: ["후기 1"],
    reviewCount: 1,
    thumbnailTone: "oliveyoung",
    thumbnailEmoji: "💄",
    bgGradient: "linear-gradient(135deg, #0ba360 0%, #3cba92 100%)",
    descriptionBullets: [
      "1. 대기줄 및 매장 질서유지",
      "2. 고객 응대지원",
      "3. 휴게시간 30분 제공",
      "4. 상시 근무 및 당일/익일 지급 가능"
    ],
    details: "명동 중심 뷰티 매장에서 저녁 시간대 고객 질서유지 및 동선 안내를 도와주실 친절한 이웃 알바님을 구합니다. 초보자도 바로 가능합니다!",
    applicantCount: 12,
    viewCount: 520,
    isFavorite: true,
    hasApplied: false,
    phoneContact: "010-8921-4321",
    isAd: true,
    createdAt: "10분 전",
  },
  {
    id: "alba-3",
    title: "[무신사스토어] 대림창고 성수 주말 피킹/물류 스태프",
    companyName: "무신사 스토어 성수점",
    neighborhoodName: "성동구 성수동2가",
    detailLocation: "성수역 3번 출구 인근",
    payType: "시급",
    payAmount: 12384,
    payLabel: "시급 12,384원",
    workingDays: "주말 (토, 일)",
    workingHours: "11:00 ~ 20:00",
    category: "걸어서10분",
    badges: ["모범구인"],
    thumbnailTone: "musinsa_dark",
    thumbnailEmoji: "📦",
    bgGradient: "linear-gradient(135deg, #09090b 0%, #27272a 100%)",
    descriptionBullets: [
      "1. 입출고 상품 분류 및 피킹",
      "2. 쾌적한 실내 창고 환경",
      "3. 주휴수당 별도 지급, 식대 지원"
    ],
    details: "성수동 핫플레이스 무신사스토어 대림창고에서 주말 동안 활기차게 함께 일할 파트타이머를 모집합니다.",
    applicantCount: 15,
    viewCount: 680,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "02-6959-1122",
    createdAt: "30분 전",
  },
  {
    id: "alba-4",
    title: "홀서빙 가족 구합니다 (초보 환영)",
    companyName: "진주꽃돼지",
    neighborhoodName: "용산구 한남동",
    detailLocation: "순천향대병원 앞 먹자골목",
    payType: "월급",
    payAmount: 3400000,
    payLabel: "월급 340만원",
    workingDays: "주 5일",
    workingHours: "16:00 ~ 02:00",
    category: "식당/카페",
    badges: ["정직원", "후기 18"],
    reviewCount: 18,
    thumbnailTone: "bbq",
    thumbnailEmoji: "🥩",
    bgGradient: "linear-gradient(135deg, #842323 0%, #d32f2f 100%)",
    descriptionBullets: [
      "1. 숯불구이 전문점 홀 서빙 및 테이블 정리",
      "2. 맛있는 저녁 식사 제공",
      "3. 팁 및 성과급 추가 지급"
    ],
    details: "동네에서 오랫동안 사랑받는 고깃집입니다. 가족처럼 편안한 분위기에서 서로 도우며 근무하실 성실한 분 환영합니다!",
    applicantCount: 6,
    viewCount: 340,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "010-3342-9988",
    createdAt: "1시간 전",
  },
  {
    id: "alba-5",
    title: "[자라] 명동 눈스퀘어점 풀타임 어드바이저 채용",
    companyName: "인디텍스코리아 자라",
    neighborhoodName: "중구 명동2가",
    detailLocation: "을지로입구역 6번 출구 연결",
    payType: "연봉",
    payAmount: 30980000,
    payLabel: "연봉 3,098만원",
    workingDays: "주 5일 (스케줄)",
    workingHours: "09:00 ~ 18:30",
    category: "이웃알바",
    badges: ["모범구인", "후기 10"],
    reviewCount: 10,
    thumbnailTone: "zara",
    thumbnailEmoji: "👗",
    bgGradient: "linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)",
    descriptionBullets: [
      "1. 글로벌 SPA 브랜드 자라 고객 어드바이징",
      "2. 디스플레이 및 매장 운영 관리",
      "3. 인센티브 및 글로벌 교육 프로그램"
    ],
    details: "글로벌 패션 그룹 인디텍스 자라에서 패션 리더로 성장할 스태프를 채용합니다.",
    applicantCount: 19,
    viewCount: 890,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "02-3783-5000",
    createdAt: "2시간 전",
  },
  {
    id: "alba-6",
    title: "디저트 전문점 카페 주5일 바리스타/스태프 모집",
    companyName: "AVA 아바",
    neighborhoodName: "성동구 성수동1가",
    detailLocation: "서울숲역 5번 출구 도보 3분",
    payType: "시급",
    payAmount: 13500,
    payLabel: "시급 13,500원",
    workingDays: "주 5일",
    workingHours: "10:00 ~ 18:00",
    category: "식당/카페",
    badges: ["모범구인", "후기 37"],
    reviewCount: 37,
    thumbnailTone: "cafe",
    thumbnailEmoji: "☕",
    bgGradient: "linear-gradient(135deg, #4b3832 0%, #854442 100%)",
    descriptionBullets: [
      "1. 스페셜티 커피 추출 및 음료 제조",
      "2. 디저트 플레이팅 및 카운터 포스 응대",
      "3. 쾌적하고 감성적인 인테리어 근무환경"
    ],
    details: "디저트와 스페셜티 커피를 사랑하는 분들의 지원을 기다립니다. 초보자도 꼼꼼한 레시피 교육 후 바로 근무 가능합니다.",
    applicantCount: 24,
    viewCount: 1040,
    isFavorite: true,
    hasApplied: true,
    phoneContact: "010-4491-0102",
    createdAt: "3시간 전",
  },
  {
    id: "alba-7",
    title: "논현 세차원 구합니다 (초보 환영, 단기 가능)",
    companyName: "텐미닛워시",
    neighborhoodName: "강남구 논현동",
    detailLocation: "학동역 1번 출구 도보 5분",
    payType: "시급",
    payAmount: 12000,
    payLabel: "시급 12,000원",
    workingDays: "협의 가능 (주 3~5일)",
    workingHours: "09:00 ~ 18:00",
    category: "물류/현장",
    badges: ["단기", "초보가능"],
    thumbnailTone: "carwash",
    thumbnailEmoji: "🚗",
    bgGradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    descriptionBullets: [
      "1. 실내외 프리미엄 디테일링 세차 보조",
      "2. 장비 사용법 1대1 맞춤 교육",
      "3. 간식 및 식사 제공"
    ],
    details: "손세차 보조 인원을 충원합니다. 땀 흘린 만큼 보람 있는 작업이며 밝고 활기찬 분위기입니다.",
    applicantCount: 4,
    viewCount: 220,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "010-9988-1234",
    createdAt: "4시간 전",
  },
  {
    id: "alba-8",
    title: "[5년연속 미슐랭] 이태원 우육미엔 홀/주방 직원",
    companyName: "우육미엔",
    neighborhoodName: "용산구 이태원동",
    detailLocation: "한강진역 1번 출구 도보 4분",
    payType: "월급",
    payAmount: 2800000,
    payLabel: "월급 280만원",
    workingDays: "주 5일 (화요일 정기휴무)",
    workingHours: "10:30 ~ 21:30 (브레이크타임 2시간)",
    category: "식당/카페",
    badges: ["정직원", "후기 1"],
    reviewCount: 1,
    thumbnailTone: "noodle",
    thumbnailEmoji: "🍜",
    bgGradient: "linear-gradient(135deg, #e52d27 0%, #b31217 100%)",
    descriptionBullets: [
      "1. 미슐랭 빕구르망 선정 대만식 우육면 전문점",
      "2. 홀 서빙 및 주방 보조",
      "3. 4대보험, 퇴직금, 유니폼 제공"
    ],
    details: "정통 대만 요리를 선보이는 우육미엔에서 성실하고 책임감 있는 팀원을 모십니다.",
    applicantCount: 7,
    viewCount: 450,
    isFavorite: false,
    hasApplied: false,
    phoneContact: "02-798-5556",
    createdAt: "5시간 전",
  }
];
